In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df1 = pd.read_excel('C:\\Users\\samre\\OneDrive\\Desktop\\Visualization\\online_retail_II.xlsx', sheet_name='Year 2009-2010')
df1.sample(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
161727,504861,21238,RED SPOTTY CUP,16,2010-04-18 12:05:00,0.85,14702.0,United Kingdom
451889,532337,84534B,FAIRY CAKE NOTEBOOK A5 SIZE,2,2010-11-11 15:49:00,0.85,13263.0,United Kingdom
186120,507121,21561,DINOSAUR LUNCH BOX WITH CUTLERY,1,2010-05-06 11:49:00,2.55,13772.0,United Kingdom
347730,523201,22666,RECIPE BOX PANTRY YELLOW DESIGN,6,2010-09-21 09:47:00,2.95,16156.0,United Kingdom
327365,521357,21937,STRAWBERRY PICNIC BAG,1,2010-09-03 16:04:00,5.91,NaN,United Kingdom
506285,536623,22029,SPACEBOY BIRTHDAY CARD,12,2010-12-02 10:39:00,0.42,15601.0,United Kingdom
479361,534387,21880,RED RETROSPOT TAPE,12,2010-11-22 12:57:00,0.65,12649.0,Germany
452905,532419,22734,SET OF 6 RIBBONS VINTAGE CHRISTMAS,4,2010-11-12 09:18:00,2.55,NaN,United Kingdom
407312,528382,21847,GREEN DIAMANTE PEN IN GIFT BOX,1,2010-10-21 18:01:00,4.21,NaN,United Kingdom
132486,501922,21421,PORCELAIN ROSE LARGE,6,2010-03-22 10:26:00,1.25,13151.0,United Kingdom

In [15]:
df2 = pd.read_excel('C:\\Users\\samre\\OneDrive\\Desktop\\Visualization\\online_retail_II.xlsx', sheet_name='Year 2010-2011')

In [16]:
df = pd.concat([df1, df2],ignore_index=True)

In [17]:
df.shape

(1067371, 8)

In [18]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [20]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,1.067371e+06,1067371,1.067371e+06,824364.000000
mean,9.938898e+00,2011-01-02 21:13:55.394028544,4.649388e+00,15324.638504
min,-8.099500e+04,2009-12-01 07:45:00,-5.359436e+04,12346.000000
25%,1.000000e+00,2010-07-09 09:46:00,1.250000e+00,13975.000000
50%,3.000000e+00,2010-12-07 15:28:00,2.100000e+00,15255.000000
75%,1.000000e+01,2011-07-22 10:23:00,4.150000e+00,16797.000000
max,8.099500e+04,2011-12-09 12:50:00,3.897000e+04,18287.000000
std,1.727058e+02,NaN,1.235531e+02,1697.464450

# Cleaning & Feature Engineering

In [22]:
df = df.dropna(subset = ['Customer ID','InvoiceDate'])

In [23]:
df.shape

(824364, 8)

In [44]:
df.sample(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
868621,566938,23267,SET OF 4 SANTA PLACE SETTINGS,48,2011-09-15 15:48:00,1.25,14557.0,United Kingdom
824943,563100,22807,SET OF 6 T-LIGHTS TOADSTOOLS,6,2011-08-12 09:57:00,2.95,12381.0,Norway
433696,530841,21231,SWEETHEART CERAMIC TRINKET BOX,12,2010-11-04 14:11:00,1.25,15298.0,United Kingdom
533195,537051,85064,CREAM SWEETHEART LETTER RACK,2,2010-12-05 11:12:00,5.45,15708.0,United Kingdom
515327,537374,20828,GLITTER BUTTERFLY CLIPS,1,2010-12-06 12:55:00,2.55,17259.0,United Kingdom
445084,531791,22386,JUMBO BAG PINK POLKADOT,20,2010-11-09 15:11:00,1.95,14841.0,United Kingdom
313601,519902,21175,GIN + TONIC DIET METAL SIGN,48,2010-08-22 13:22:00,1.85,13225.0,United Kingdom
474190,534049,22274,FELTCRAFT DOLL EMILY,6,2010-11-19 17:21:00,2.95,12578.0,Italy
46352,493695,21294,ETCHED GLASS COASTER,5,2010-01-05 13:23:00,1.25,14606.0,United Kingdom
918623,570806,22751,FELTCRAFT PRINCESS OLIVIA DOLL,4,2011-10-12 12:42:00,3.75,13115.0,United Kingdom

In [35]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

In [36]:
df.shape

(805620, 8)

In [48]:
df = df[df['Quantity'] > 0]
df = df[df['Price'] > 0]

In [46]:
df.shape

(805620, 8)

In [49]:
df.shape

(805549, 8)

In [50]:
805620 - 805549

71